# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: skagedal's oboy
email: skagedal@gmail.com
description: >
  Thoughts on programming, music and other things. Feel free to e-mail me comments!
baseurl: ""
url: "https://blog.skagedal.tech"
twitter_username: skagedal
github_username:  skagedal

# Build settings
markdown: kramdown
