{
  name: 'Main CI job',
  on: {
    push: {
      branches: [ "main" ]
    }
  },
  jobs: {
    build: {
      runs-on: 'ubuntu-latest',
      steps: [
        {
          id: 'checkout',
          name: 'Checkout repository',
          uses: 'actions/checkout@v4'
        },
        {
          id: 'jdk',
          name: 'Set up JDK',
          uses: 'actions/setup-java@v4',
          with: {
            java-version: '24',
            distribution: 'temurin',
            cache: 'maven'
          }
        },
        {
          id: 'ssh',
          name: 'Set up SSH',
          env: {
            SSH_KEY: '${{ secrets.SSH_KEY }}',
            SSH_KNOWN_HOSTS: '${{ secrets.SSH_KNOWN_HOSTS }}'
          },
          run: './ci/setup-ssh.sh'
        },
        {
          id: 'build',
          name: 'Build with Maven',
          working-directory: 'blogdans',
          run: 'mvn -B package assembly:single --file pom.xml'
        },
        {
          id: 'upload',
          name: 'Upload files',
          run: './ci/upload-blogdans-files.sh'
        },
        {
          id: 'restart',
          name: 'Restart service',
          run: 'ssh blogdans ./restart.sh'
        },
        {
          id: 'report-success',
          name: 'Report success',
          env: {
            SLACK_WEBHOOK_URL: '${{ secrets.SLACK_WEBHOOK_URL }}'
          },
          run: './ci/report-success.sh'
        }
      ]
    }
  }
}